version: "3.10"

services:
  db:
    image: postgres
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=medintDB
    env_file: .env
  redis:
    image: redis
    container_name: redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server --save 60 1 --requirepass ${REDIS_PASSWORD}
    networks:
      - net
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - ${PORT_SERVER}:${PORT_SERVER}
    depends_on:
      - db
      - redis
    env_file: .env
    command: sh -c 'python main.py'
networks:
  net:
    driver: bridge

